#!/usr/bin/env python3

from http.server import SimpleHTTPRequestHandler, HTTPServer
import os, sys

class SPAHandler(SimpleHTTPRequestHandler):
	def do_GET(self):
		if self.path == '/' or not os.path.exists(self.translate_path(self.path)):
			self.path = '/index.html'
		return super().do_GET()


ADDR = sys.argv[1]
PORT = int(sys.argv[2])

dir_path = os.path.dirname(os.path.realpath(__file__))
os.chdir(dir_path)

server = HTTPServer((ADDR, PORT), SPAHandler)
print(f"Serving SPA on http://{ADDR}:{PORT}", file=sys.stderr)
sys.stderr.flush()
server.serve_forever()
